backend:
  name: git-gateway
media_folder: 'source/images/uploads'
public_folder: '/images/uploads'
collections:
  - label: City Pages
    name: city_pages
    folder: data/city_pages
    create: true
    fields:
      - { label: Tagline, name: tagline, widget: string, required: true }
