backend:
  name: git-gateway
media_folder: 'source/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: city_pages
    label: City Pages
    label_singular: City Page
    identifier_field: de.title
    folder: data/city_pages/
    extension: yml
    create: true
    preview_path: "{{slug}}"
    fields:
      - { label: Title (DE), name: de.title, widget: string, required: true }
      - { label: Title (EN), name: en.title, widget: string, required: true }
      - { label: Description (DE), name: de.description, widget: text, required: true }
      - { label: Description (EN), name: en.description, widget: text, required: true }
      - { label: Tagline (DE), name: de.tagline, widget: string, required: true }
      - { label: Tagline (EN), name: en.tagline, widget: string, required: true }
